### ISSUE TITLE
Various Questions

### ISSUE THREAD

**Issue by danglotb** [abel-vs/browser-energy-measurer#1]
Hello guys,

Great project! I loved it! Very interesting.

I have some questions:

1. Do you know if there is so instability with the energy consumption measurements done with PowerGadget as we do observe with RAPL on Linux?

2. Do you plan to compare the measurements on various platforms: _e.g._ MacOS vs Windows?

3. Is there any reason you do 10x3 runs for each browser: https://github.com/abel-vs/browser-energy-measurer/blob/2526b452e0f33e117f9b81c36e7fc39ff64dadd2/run.ps1#L8-L12

Rather than just making 30 runs for each browser?

4. Do you have any references to support the need for warm-up?
https://github.com/abel-vs/browser-energy-measurer/blob/2526b452e0f33e117f9b81c36e7fc39ff64dadd2/run.ps1#L2

Thank you very much! Have a nice day :smile:

**Comment by abel-vs** [comment]
Hey Benjamin, thanks for your interest!

1. The measurements we obtained from PowerGadget didn't show signs of significant instability. There is some variance in the performance of the browsers (shown in the boxplot images), but we attribute this to the browsers themselves and not to the PowerGadget tool.

2. This project was developed for the "Sustainable Software Engineering" course from the TU Delft. We are currently not planning on extending our research towards other platforms.  

3. The 3x10 setup is for controlling external influences, such as changes in internet speeds or uncontrolled background processes. We set up the run environment to be as reliable as possible, by disabling background processes and other applications, but there may always be some external variabilities influencing the experiment. 
For this we alternate between the browsers, so that an external influence would influence each browser equally. If we did 30 consecutive runs, such an influence might only affect one browser, which would make the results less reliable.
We chose to execute the runs in batches of 3 to simulate the effect of multiple browse sessions per browser. If we chose to run in batches of 1 run, a potential accumulating effect on performance would get lost.
We chose 3x10 as a balance between a 30x1 consecutive runs,  and a 1x30 fully alternating setup.

4. The warm-up procedure avoids that the first runs are run on an abnormal cold or hot CPU. This is again for reliability, to make sure the run environment is equal for each run of each browser. We based this on energy experimentation guidelines from the course. 

If you are interested in how we designed our energy experiments to be reliable, I would suggest checking out this [presentation](https://surfdrive.surf.nl/files/index.php/s/WAwaYYSsn04Pxdi) from the aforementioned course "Sustainable Software Engineering" from the TU Delft, taught by @luiscruz.

Hopefully this made things more clear, if you have any other questions feel free to ask! :)

**Comment by danglotb** [comment]
Hello @abel-vs 

Thank you very much for your answers! They are very accurate.

> The 3x10 setup is for controlling external influences, such as changes in internet speeds or uncontrolled background processes. We set up the run environment to be as reliable as possible, by disabling background processes and other applications, but there may always be some external variabilities influencing the experiment.

From my point of view, the external influences are "instability" in the measurements. What I mean is that it seems that both PowerGadget and RAPL measure the energy consumption of the whole CPU, and we cannot (yet) isolate by processes.

Therefore, you need to set up the `zen mode`, as @luiscruz explained, and even if such precautions, you are still subject to variations due to things that are uncontrollable (_e.g._ the OS does things automatically).

That's great! Thank you very much. Hope we can discuss again soon :smiley:
